// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: control.proto

package controlproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest is sent by a client right after the control-channel QUIC
// handshake completes, to announce its identity to the rendezvous server.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes, Curve25519/WireGuard-compatible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// RegisterResponse tells the client how the server sees it, i.e. its
// server-reflexive candidate — the STUN-equivalent part of registration.
type RegisterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ObservedAddress string                 `protobuf:"bytes,2,opt,name=observed_address,json=observedAddress,proto3" json:"observed_address,omitempty"` // host:port as seen by the server
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RegisterResponse) GetObservedAddress() string {
	if x != nil {
		return x.ObservedAddress
	}
	return ""
}

// Candidate mirrors domain.Candidate on the wire.
type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`       // "host" | "server_reflexive" | "relay"
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // ip:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Candidate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// PublishCandidatesRequest sends the caller's own candidates for a session,
// identified by a session ID both peers derive independently
// (domain.SessionIDFor) from their two peer IDs.
type PublishCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // the publisher's own ID
	Candidates    []*Candidate           `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCandidatesRequest) Reset() {
	*x = PublishCandidatesRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCandidatesRequest) ProtoMessage() {}

func (x *PublishCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCandidatesRequest.ProtoReflect.Descriptor instead.
func (*PublishCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *PublishCandidatesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PublishCandidatesRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PublishCandidatesRequest) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type PublishCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCandidatesResponse) Reset() {
	*x = PublishCandidatesResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCandidatesResponse) ProtoMessage() {}

func (x *PublishCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCandidatesResponse.ProtoReflect.Descriptor instead.
func (*PublishCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

// AwaitCandidatesRequest blocks server-side until peer_id's candidates for
// session_id have been published, or the stream's context is cancelled.
type AwaitCandidatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // whose candidates the caller is waiting for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitCandidatesRequest) Reset() {
	*x = AwaitCandidatesRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitCandidatesRequest) ProtoMessage() {}

func (x *AwaitCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitCandidatesRequest.ProtoReflect.Descriptor instead.
func (*AwaitCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *AwaitCandidatesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AwaitCandidatesRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type AwaitCandidatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitCandidatesResponse) Reset() {
	*x = AwaitCandidatesResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitCandidatesResponse) ProtoMessage() {}

func (x *AwaitCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitCandidatesResponse.ProtoReflect.Descriptor instead.
func (*AwaitCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *AwaitCandidatesResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// RelayOpenRequest is the only framed message on a relay stream: after the
// server reads it, the rest of the QUIC stream is treated as an opaque
// byte pipe and spliced to the counterpart's stream for the same session.
// There is no RelayOpenResponse — bytes just start flowing once both
// sides of the session have opened their stream.
type RelayOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayOpenRequest) Reset() {
	*x = RelayOpenRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayOpenRequest) ProtoMessage() {}

func (x *RelayOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayOpenRequest.ProtoReflect.Descriptor instead.
func (*RelayOpenRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *RelayOpenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// MeshMember mirrors domain.MeshMember on the wire.
type MeshMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MeshIp        string                 `protobuf:"bytes,3,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshMember) Reset() {
	*x = MeshMember{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshMember) ProtoMessage() {}

func (x *MeshMember) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshMember.ProtoReflect.Descriptor instead.
func (*MeshMember) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *MeshMember) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *MeshMember) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MeshMember) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

// JoinNetworkRequest asks the server to join (or auto-create) a mesh
// network by name. There is no invite-token gating yet (see
// usecase.JoinNetwork's doc comment) — Phase 7.
type JoinNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkName   string                 `protobuf:"bytes,1,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNetworkRequest) Reset() {
	*x = JoinNetworkRequest{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNetworkRequest) ProtoMessage() {}

func (x *JoinNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNetworkRequest.ProtoReflect.Descriptor instead.
func (*JoinNetworkRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *JoinNetworkRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *JoinNetworkRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type JoinNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Members       []*MeshMember          `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"` // includes the caller itself
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNetworkResponse) Reset() {
	*x = JoinNetworkResponse{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNetworkResponse) ProtoMessage() {}

func (x *JoinNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNetworkResponse.ProtoReflect.Descriptor instead.
func (*JoinNetworkResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *JoinNetworkResponse) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *JoinNetworkResponse) GetMembers() []*MeshMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\n" +
	"control.v1\"0\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\"V\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12)\n" +
	"\x10observed_address\x18\x02 \x01(\tR\x0fobservedAddress\"9\n" +
	"\tCandidate\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x89\x01\n" +
	"\x18PublishCandidatesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x125\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x15.control.v1.CandidateR\n" +
	"candidates\"\x1b\n" +
	"\x19PublishCandidatesResponse\"P\n" +
	"\x16AwaitCandidatesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\"P\n" +
	"\x17AwaitCandidatesResponse\x125\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x15.control.v1.CandidateR\n" +
	"candidates\"1\n" +
	"\x10RelayOpenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"]\n" +
	"\n" +
	"MeshMember\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x17\n" +
	"\amesh_ip\x18\x03 \x01(\tR\x06meshIp\"V\n" +
	"\x12JoinNetworkRequest\x12!\n" +
	"\fnetwork_name\x18\x01 \x01(\tR\vnetworkName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"[\n" +
	"\x13JoinNetworkResponse\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x120\n" +
	"\amembers\x18\x02 \x03(\v2\x16.control.v1.MeshMemberR\amembersB<Z:github.com/fu1se/localizator/internal/adapter/controlprotob\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_control_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: control.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 1: control.v1.RegisterResponse
	(*Candidate)(nil),                 // 2: control.v1.Candidate
	(*PublishCandidatesRequest)(nil),  // 3: control.v1.PublishCandidatesRequest
	(*PublishCandidatesResponse)(nil), // 4: control.v1.PublishCandidatesResponse
	(*AwaitCandidatesRequest)(nil),    // 5: control.v1.AwaitCandidatesRequest
	(*AwaitCandidatesResponse)(nil),   // 6: control.v1.AwaitCandidatesResponse
	(*RelayOpenRequest)(nil),          // 7: control.v1.RelayOpenRequest
	(*MeshMember)(nil),                // 8: control.v1.MeshMember
	(*JoinNetworkRequest)(nil),        // 9: control.v1.JoinNetworkRequest
	(*JoinNetworkResponse)(nil),       // 10: control.v1.JoinNetworkResponse
}
var file_control_proto_depIdxs = []int32{
	2, // 0: control.v1.PublishCandidatesRequest.candidates:type_name -> control.v1.Candidate
	2, // 1: control.v1.AwaitCandidatesResponse.candidates:type_name -> control.v1.Candidate
	8, // 2: control.v1.JoinNetworkResponse.members:type_name -> control.v1.MeshMember
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
